import React from "react";
import Head from "next/head";

import { useMediaQuery } from "@material-ui/core";

import Header from "../Header";
import Footer from "../Footer";
import Wave from "../Wave";

import { MuiTheme } from "../../styles/theme";
import { StyledContainer } from "./styles.js";

export default function PageTemplate({ isHome, children }) {
  const isMobile = useMediaQuery(MuiTheme.breakpoints.down("sm"));

  return (
    <>
      <Head>
        <title>Computer Progress</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isHome={isHome} />

      {isHome && !isMobile ? <Wave /> : null}

      <StyledContainer>{children}</StyledContainer>

      <Footer />
    </>
  );
}
