import React, { useState } from "react";
import Head from "next/head";
import { Container, Header, Page } from "./styles.js";
import NavBar from "../NavBar";
import Wave from "../Wave";
import Footer from "../Footer";

export default function PageTemplate({ isHome, children }) {
  return (
    <Page>
      <Head>
        <title>Computer Progress</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <NavBar transparentBackground={isHome} />
        {isHome ? (
          <Wave />
        ) : null}
      </Header>
      <Container>
        {children}
      </Container>
      <Footer home={isHome} />
    </Page>
  );
}
