import Head from "next/head";
import { Container } from "./styles.js";
import SecondaryNavbar from "../../components/SecondaryNavbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Computer Progress</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SecondaryNavbar />
      <Container></Container>

      <footer></footer>
    </div>
  );
}