import React, { useState } from "react";
import Head from "next/head";
import { Container } from "./styles.js";
import NavBar from "../../components/NavBar";
import Wave from "../../components/Wave";
import Footer from "../../components/Footer";
import Chart from "../../components/Chart";
import Tabs from "../../components/Tabs";
import StateOfArtBox from "../../components/StateOfArtBox";
import Button from "../../components/Button"
import Collaborate from "../../components/Collaborate";

import {
  imagenet,
  mscoco,
  squad1_1,
  conll2003,
  wmt2014_enfr,
  wmt2014_enge,
} from "../../data";
import theme from "../../styles/theme.js";

export default function Home() {
  const [data, setData] = useState(imagenet);
  const [label, setLabel] = useState("TOP 1");
  const [selected, setSelected] = useState(0);
  const [buttons, setButtons] = useState([
    {
      label: "Imagenet",
      onPress: () => { },
    },
  ]);

  const tabs = [
    {
      name: "Image Classification",
      onSelect: () => {
        setData(imagenet);
        setLabel("TOP 1");
        setSelected(0);
        setButtons([
          {
            name: "Imagenet",
            onPress: () => { },
          },
        ]);
      },
    },
    {
      name: "Object Detection",
      onSelect: () => {
        setData(mscoco);
        setLabel("BOX AP");
        setSelected(1);
        setButtons([
          {
            name: "MS COCO",
            onPress: () => { },
          },
        ]);
      },
    },
    {
      name: "Question Answering",
      onSelect: () => {
        setData(squad1_1);
        setLabel("F1 SCORE");
        setSelected(2);
        setButtons([
          {
            name: "SQUAD 1.1",
            onPress: () => { },
          },
        ]);
      },
    },
    {
      name: "Named Entity Recognition",
      onSelect: () => {
        setData(conll2003);
        setLabel("F1 SCORE");
        setSelected(3);
        setButtons([
          {
            name: "Conll 2003",
            onPress: () => { },
          },
        ]);
      },
    },
    {
      name: "Machine Translation",
      onSelect: () => {
        setData(wmt2014_enfr);
        setLabel("BLEU");
        setSelected(4);
        setButtons([
          {
            name: "WMT 2014 EN-FR",
            onPress: () => {
              setData(wmt2014_enfr);
              setLabel("BLEU");
            },
          },
          {
            name: "WMT 2014 EN-GE",
            onPress: () => {
              setData(wmt2014_enge);
              setLabel("BLEU");
            },
          },
        ]);
      },
    },
  ];

  return (
    <div>
      <Head>
        <title>Computer Progress</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Wave />
      <Container>
        <Tabs selected={selected} items={tabs} />
        <Button color={theme.colors.black}>VIEW ALL DOMAINS</Button>
        <Chart data={data} label={label} />
        <StateOfArtBox data={data} />
      </Container>
      <Collaborate/>
      <Footer />
    </div>
  );
}
