import Head from "next/head";
import Link from "next/link";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
export default function Home() {
  return (
    <>
      <div className="min-h-screen flex flex-col">
        <Head>
          <title>Computer Progress</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar className=" z-30"></Navbar>
        <div className="  relative flex flex-col items-center min-w-screen justify-end flex-1">
          <div className=" z-30 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 flex-1 flex items-center">
            <div className="">
              <h2 className="text-white text-3xl font-bold">
                We’re a team working to understand the economic and technical
                foundations of progress in computing.
              </h2>
              <div className="mt-5">
                <Link href={"/benchmarks/image-classification-on-imagenet"}>
                  <button className="border-2 bg-black/50 hover:bg-black border-gray-100 flex gap-1 text-sm text-white px-3 py-2 rounded-lg focus:ring-2 outline-none  focus:ring-gray-100 ring-offset-1 ring-opacity-25">
                    Learn more
                  </button>
                </Link>
              </div>
            </div>
          </div>
          <div className="video-docker absolute top-0 left-0 w-full h-full overflow-hidden">
            <video
              className="min-w-full min-h-full absolute object-cover"
              src="/hero.webm"
              type="video/mp4"
              autoPlay
              muted
              loop
            ></video>
          </div>
 
        </div>
          <Footer   />
      </div>
    </>
  );
}

// export async function getStaticProps(context) {
//   const dataset = await getDataset();

//   return {
//     props: {
//       dataset,
//     },
//     // Next.js will attempt to re-generate the page:
//     // - When a request comes in
//     // - At most once every second
//     revalidate: 30, // In seconds
//   };
// }
