import Head from "next/head";
import Navbar from "../components/Navbar";
import Header from "../components/trends/Header";
import Chart from "../components/trends/Chart";
import Footer from "../components/Footer";
// import { getDataset } from "../lib/api";

export default function Home({ }) {

  return (
    <div>
      <Head>
        <title>Parameter, Compute and Data Trends in Machine Learning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <div className="min-h-full">
        <Navbar></Navbar>
        <Header></Header>
        <Chart />

        <Footer />
      </div>
    </div>
  );
}

// export async function getStaticProps({ params }) {
//   const spreadsheetId = "1N5CHCc9tuRKOzFrzdAWrG9_u9RbXDoCYXbaGvb-kbu0";

//   const dataset = await getDataset("NOTABLE ML SYSTEMS", spreadsheetId);

//   return {
//     props: {
//       dataset,
//     },
//     // Next.js will attempt to re-generate the page:
//     // - When a request comes in
//     // - At most once every second
//     revalidate: 60, // In seconds
//   };
// }
