import Head from "next/head";
import Navbar from "../components/Navbar";
import Header from "../components/trends/Header";
import Main from "../components/trends/Main";
import Footer from "../components/Footer";
import { getDataset } from "../lib/api";
import { init } from "../components/trends/graph/trends";
export default function Home({ dataset }) {
  return (
    <div>
      <Head>
        <title>Parameter, Compute and Data Trends in Machine Learning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-full">
        <Navbar></Navbar>
        <Header></Header>
        <Main dataset={dataset} />

        <Footer />
      </div>
    </div>
  );
}

export async function getStaticProps({ params }) {
  const spreadsheetId = "1N5CHCc9tuRKOzFrzdAWrG9_u9RbXDoCYXbaGvb-kbu0";

  const data = await getDataset("NOTABLE ML SYSTEMS", spreadsheetId);
  const dataset = data.slice(1).map((row) => {
    const rowObject = {};
    row.forEach((column, i) => {
      rowObject[data[0][i]] = column.trim();
    });
    rowObject["Training compute per parameter (FLOPs)"] =
      rowObject["Training compute (FLOPs)"] / rowObject["Parameters"];
    rowObject["Training compute times parameters"] =
      rowObject["Training compute (FLOPs)"] * rowObject["Parameters"];
    return rowObject;
  });

  return {
    props: {
      dataset,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every second
    revalidate: 60, // In seconds
  };
}
