name: PR-main
on:
  pull_requests:
    branches:
      - main
jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:ci
